[alembic]
# Ruta al directorio donde residen env.py y la carpeta versions/
script_location = alembic

# Añade el directorio raíz del proyecto a sys.path
prepend_sys_path = .

# Separador de rutas para las revisiones
version_path_separator = os

# URL por defecto a la base de datos SQLite
sqlalchemy.url = sqlite:///bot_database.db

[post_write_hooks]

# Configuración de Logging
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
