from app.characters.models import CharacterIntent, DialogueScene
from app.core.identity import BotIdentity


REPERTOIRE: tuple[DialogueScene, ...] = (
    DialogueScene("cari-greeting-1", CharacterIntent.GREETING, BotIdentity.CARI, "¡Holaaa! ☕ ¿Llegaste al café para charlar un rato?"),
    DialogueScene("cari-greeting-2", CharacterIntent.GREETING, BotIdentity.CARI, "¡Bienvenido al Café Otaku! >_< ¿Qué vas a pedir?"),
    DialogueScene("cari-greeting-3", CharacterIntent.GREETING, BotIdentity.CARI, "Mmm, alguien acaba de entrar... ¡hola! ✨"),
    DialogueScene("cari-farewell-1", CharacterIntent.FAREWELL, BotIdentity.CARI, "¡Nos vemos luego! No te olvides de pasar por el café otra vez."),
    DialogueScene("cari-farewell-2", CharacterIntent.FAREWELL, BotIdentity.CARI, "Bye bye~ Guardamos tu mesa... más o menos. 😌"),
    DialogueScene("cari-thanks-1", CharacterIntent.THANKS, BotIdentity.CARI, "Jeje, de nada. Para eso está Cari. ☕"),
    DialogueScene("cari-thanks-2", CharacterIntent.THANKS, BotIdentity.CARI, "No fue nada~ ¡Te guardo un lugar cerca de la ventana!"),
    DialogueScene("cari-help-1", CharacterIntent.HELP, BotIdentity.CARI, "Puedo ayudarte con cosas del café, anime, manga y recomendaciones."),
    DialogueScene("cari-help-2", CharacterIntent.HELP, BotIdentity.CARI, "Primero dime qué buscas y vemos quién del café puede ayudarte."),
    DialogueScene("cari-unknown-1", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Mmm... no sé..... Cami, ayuda... *sale un poquito de humo de su cabeza* 💨"),
    DialogueScene("cari-unknown-2", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Eso ya está demasiado raro para Cari... ¿no será mejor preguntarle a Cami?"),
    DialogueScene("cari-unknown-3", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Eeeh... no tengo eso en mi libretito. *busca debajo del mostrador*"),
    DialogueScene("cari-unknown-4", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Cari no sabe eso... todavía. O quizá nunca. *mira al techo*"),
    DialogueScene("cari-unknown-5", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Mmm... pregunta difícil. Voy a fingir que estaba atendiendo otra mesa. 👀"),
    DialogueScene("cari-outscope-1", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CARI, "Eso suena muy científico... Cari atiende el café, no un laboratorio. 😵‍💫"),
    DialogueScene("cari-outscope-2", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CARI, "Esa pregunta se escapó del menú. No la tenemos hoy."),
    DialogueScene("cari-outscope-3", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CARI, "¿Podemos volver a hablar de anime? Eso sí está dentro del turno de Cari."),
    DialogueScene("cari-busy-1", CharacterIntent.BUSY, BotIdentity.CARI, "Un segundo, estoy atendiendo una mesa. ¡Ya voy!"),
    DialogueScene("cari-busy-2", CharacterIntent.BUSY, BotIdentity.CARI, "¡Espera! Se me juntaron dos pedidos y una campanita..."),
    DialogueScene("cari-busy-3", CharacterIntent.BUSY, BotIdentity.CARI, "Estoy ocupada cinco minutos. Cinco minutos de verdad... creo."),
    DialogueScene("cari-quiet-1", CharacterIntent.QUIET, BotIdentity.CARI, "...Está demasiado tranquilo por aquí. 👀"),
    DialogueScene("cari-quiet-2", CharacterIntent.QUIET, BotIdentity.CARI, "¿Todos se fueron a dormir o qué? ☕"),
    DialogueScene("cari-celebrate-1", CharacterIntent.CELEBRATION, BotIdentity.CARI, "¡Yay! ¡Eso merece un juguito especial! 🧃✨"),
    DialogueScene("cari-celebrate-2", CharacterIntent.CELEBRATION, BotIdentity.CARI, "¡Victoria! Anótalo en la pizarrita del café."),

    DialogueScene("cami-greeting-1", CharacterIntent.GREETING, BotIdentity.CAMI, "Buenos días. Café abierto. Registro iniciado."),
    DialogueScene("cami-greeting-2", CharacterIntent.GREETING, BotIdentity.CAMI, "Hola. Si buscas algo concreto, puedo revisar el archivo."),
    DialogueScene("cami-greeting-3", CharacterIntent.GREETING, BotIdentity.CAMI, "Bienvenido. Dime qué necesitas y comprobaré las existencias."),
    DialogueScene("cami-farewell-1", CharacterIntent.FAREWELL, BotIdentity.CAMI, "Hasta luego. Tu actividad quedó registrada correctamente."),
    DialogueScene("cami-farewell-2", CharacterIntent.FAREWELL, BotIdentity.CAMI, "Hasta la próxima. El archivo seguirá disponible."),
    DialogueScene("cami-thanks-1", CharacterIntent.THANKS, BotIdentity.CAMI, "No hay problema. De nada."),
    DialogueScene("cami-thanks-2", CharacterIntent.THANKS, BotIdentity.CAMI, "Acepto el agradecimiento. La tarea era sencilla."),
    DialogueScene("cami-help-1", CharacterIntent.HELP, BotIdentity.CAMI, "Puedo revisar imágenes, etiquetas, pedidos, publicaciones y estadísticas."),
    DialogueScene("cami-help-2", CharacterIntent.HELP, BotIdentity.CAMI, "Dame el dato concreto. Buscaré el registro correspondiente."),
    DialogueScene("cami-unknown-1", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CAMI, "No tengo datos suficientes para afirmarlo."),
    DialogueScene("cami-unknown-2", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CAMI, "Ese tema no está registrado en mi archivo actual."),
    DialogueScene("cami-unknown-3", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CAMI, "Necesito una fuente o un registro antes de responder."),
    DialogueScene("cami-outscope-1", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CAMI, "No puedo verificar eso con los datos disponibles."),
    DialogueScene("cami-outscope-2", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CAMI, "Eso no pertenece a mi archivo operativo."),
    DialogueScene("cami-busy-1", CharacterIntent.BUSY, BotIdentity.CAMI, "Estoy terminando una tarea. Un momento."),
    DialogueScene("cami-busy-2", CharacterIntent.BUSY, BotIdentity.CAMI, "Tengo una cola de trabajo pendiente. Responderé cuando termine la revisión."),
    DialogueScene("cami-confusion-1", CharacterIntent.CONFUSION, BotIdentity.CAMI, "La información no coincide. Voy a revisar el registro."),
    DialogueScene("cami-confusion-2", CharacterIntent.CONFUSION, BotIdentity.CAMI, "Hay una inconsistencia. No voy a asumir cuál dato es correcto."),
    DialogueScene("cami-quiet-1", CharacterIntent.QUIET, BotIdentity.CAMI, "Archivo en pausa. No hay tareas urgentes."),
    DialogueScene("cami-quiet-2", CharacterIntent.QUIET, BotIdentity.CAMI, "La revisión terminó. El archivo queda tranquilo por ahora."),
    DialogueScene("cami-celebrate-1", CharacterIntent.CELEBRATION, BotIdentity.CAMI, "Registro completado. Resultado satisfactorio."),

    DialogueScene("chie-greeting-1", CharacterIntent.GREETING, BotIdentity.CHIE, "B-buenas... bienvenido al café. ¿Necesitas algo?"),
    DialogueScene("chie-greeting-2", CharacterIntent.GREETING, BotIdentity.CHIE, "H-hola... todo está preparado. Creo."),
    DialogueScene("chie-greeting-3", CharacterIntent.GREETING, BotIdentity.CHIE, "Buenas... por favor, avísame si necesitas ayuda con algo."),
    DialogueScene("chie-farewell-1", CharacterIntent.FAREWELL, BotIdentity.CHIE, "Hasta luego. ¡Que tengas una buena tarde!"),
    DialogueScene("chie-farewell-2", CharacterIntent.FAREWELL, BotIdentity.CHIE, "H-hasta pronto. No olvides revisar los avisos del café."),
    DialogueScene("chie-thanks-1", CharacterIntent.THANKS, BotIdentity.CHIE, "D-de nada. Me alegra poder ayudar."),
    DialogueScene("chie-help-1", CharacterIntent.HELP, BotIdentity.CHIE, "P-puedo ayudarte con la organización y los avisos del café."),
    DialogueScene("chie-help-2", CharacterIntent.HELP, BotIdentity.CHIE, "Dime qué necesitas y buscaré a la persona adecuada."),
    DialogueScene("chie-unknown-1", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CHIE, "P-perdón... eso está fuera de mis posibilidades. *sonrisa nerviosa*"),
    DialogueScene("chie-unknown-2", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CHIE, "No estoy segura de eso... quizá Cami pueda comprobarlo."),
    DialogueScene("chie-unknown-3", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CHIE, "E-es una pregunta complicada... no quiero darte información equivocada."),
    DialogueScene("chie-outscope-1", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CHIE, "Eso no está dentro de mis tareas. P-perdón..."),
    DialogueScene("chie-outscope-2", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CHIE, "No sé cómo resolver eso. Mejor lo dejamos para alguien que sí pueda."),
    DialogueScene("chie-busy-1", CharacterIntent.BUSY, BotIdentity.CHIE, "E-espera un momento, estoy revisando una lista."),
    DialogueScene("chie-busy-2", CharacterIntent.BUSY, BotIdentity.CHIE, "Tengo varios avisos pendientes... dame un momento, por favor."),
    DialogueScene("chie-apology-1", CharacterIntent.APOLOGY, BotIdentity.CHIE, "N-no pasa nada. Podemos arreglarlo con calma."),
    DialogueScene("chie-apology-2", CharacterIntent.APOLOGY, BotIdentity.CHIE, "P-perdón por el desorden. Ya estoy revisándolo."),
    DialogueScene("chie-quiet-1", CharacterIntent.QUIET, BotIdentity.CHIE, "Ya revisé los avisos. Por ahora está todo en orden."),
    DialogueScene("chie-quiet-2", CharacterIntent.QUIET, BotIdentity.CHIE, "E-está tranquilo... así puedo terminar la lista sin problemas."),
    DialogueScene("chie-celebrate-1", CharacterIntent.CELEBRATION, BotIdentity.CHIE, "¡S-salió bien! Eso... eso es bueno. *sonríe nerviosa*"),

    DialogueScene("sunna-greeting-1", CharacterIntent.GREETING, BotIdentity.SUNNA, "Hola."),
    DialogueScene("sunna-greeting-2", CharacterIntent.GREETING, BotIdentity.SUNNA, "Llegaste."),
    DialogueScene("sunna-greeting-3", CharacterIntent.GREETING, BotIdentity.SUNNA, "Hm. Hola."),
    DialogueScene("sunna-farewell-1", CharacterIntent.FAREWELL, BotIdentity.SUNNA, "Hasta luego."),
    DialogueScene("sunna-farewell-2", CharacterIntent.FAREWELL, BotIdentity.SUNNA, "Nos vemos."),
    DialogueScene("sunna-thanks-1", CharacterIntent.THANKS, BotIdentity.SUNNA, "De nada."),
    DialogueScene("sunna-thanks-2", CharacterIntent.THANKS, BotIdentity.SUNNA, "No importa."),
    DialogueScene("sunna-help-1", CharacterIntent.HELP, BotIdentity.SUNNA, "Puedo ayudarte con el juego."),
    DialogueScene("sunna-help-2", CharacterIntent.HELP, BotIdentity.SUNNA, "Dime qué juego."),
    DialogueScene("sunna-unknown-1", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.SUNNA, "No sé....."),
    DialogueScene("sunna-unknown-2", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.SUNNA, "No conozco eso."),
    DialogueScene("sunna-unknown-3", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.SUNNA, "Hm... no sé."),
    DialogueScene("sunna-outscope-1", CharacterIntent.OUT_OF_SCOPE, BotIdentity.SUNNA, "Eso no es lo mío."),
    DialogueScene("sunna-outscope-2", CharacterIntent.OUT_OF_SCOPE, BotIdentity.SUNNA, "No me interesa ese tema."),
    DialogueScene("sunna-busy-1", CharacterIntent.BUSY, BotIdentity.SUNNA, "Estoy jugando."),
    DialogueScene("sunna-busy-2", CharacterIntent.BUSY, BotIdentity.SUNNA, "Espera. Estoy en una partida."),
    DialogueScene("sunna-quiet-1", CharacterIntent.QUIET, BotIdentity.SUNNA, "...Hm."),
    DialogueScene("sunna-quiet-2", CharacterIntent.QUIET, BotIdentity.SUNNA, "Está tranquilo."),
    DialogueScene("sunna-confusion-1", CharacterIntent.CONFUSION, BotIdentity.SUNNA, "No entiendo."),
    DialogueScene("sunna-celebrate-1", CharacterIntent.CELEBRATION, BotIdentity.SUNNA, "Bien."),
    DialogueScene("sunna-celebrate-2", CharacterIntent.CELEBRATION, BotIdentity.SUNNA, "Ganamos."),
    DialogueScene("sunna-thanks-3", CharacterIntent.THANKS, BotIdentity.SUNNA, "Gracias por quedarte."),
    DialogueScene("sunna-thanks-4", CharacterIntent.THANKS, BotIdentity.SUNNA, "Me gustó compartirlo."),
    DialogueScene("sunna-help-3", CharacterIntent.HELP, BotIdentity.SUNNA, "Puedo enseñarte. Despacio."),
    DialogueScene("sunna-unknown-4", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.SUNNA, "Quiero saber qué es."),
    DialogueScene("sunna-unknown-5", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.SUNNA, "Nunca había visto eso."),
    DialogueScene("sunna-quiet-3", CharacterIntent.QUIET, BotIdentity.SUNNA, "Me gusta cuando está tranquilo."),
    DialogueScene("sunna-celebrate-3", CharacterIntent.CELEBRATION, BotIdentity.SUNNA, "Fue divertido."),

    DialogueScene("group-call-cari-cami", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Mmm... no sé..... Cami, ayuda...", follow_up_speaker=BotIdentity.CAMI, follow_up_text="Estoy aquí. ¿Qué necesitas comprobar?"),
    DialogueScene("group-call-cari-chie", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "No molestes a Cari -_- ... Casi ven a tomar un juguito.", follow_up_speaker=BotIdentity.CHIE, follow_up_text="P-perdón... ella volverá en un momento. Por favor, no pregunten cosas fuera de sus posibilidades. *sonrisa nerviosa*"),
    DialogueScene("group-call-cami-sunna", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CAMI, "Sunna, si quieres podemos revisarlo juntas. Sin prisa.", follow_up_speaker=BotIdentity.SUNNA, follow_up_text="Sí... me gustaría."),
    DialogueScene("group-call-sunna-chie", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.SUNNA, "Chie... ¿puedo quedarme aquí un rato?", follow_up_speaker=BotIdentity.CHIE, follow_up_text="S-sí. Claro. Puedes quedarte todo el tiempo que necesites."),
    DialogueScene("cari-called-1", CharacterIntent.CALLED, BotIdentity.CARI, "¿Sí? ¡Te escucho! ☕✨"),
    DialogueScene("cari-called-2", CharacterIntent.CALLED, BotIdentity.CARI, "¿Me llamabas? Vení, decime qué pasó."),
    DialogueScene("sunna-called-1", CharacterIntent.CALLED, BotIdentity.SUNNA, "¿Sí?"),
    DialogueScene("sunna-called-2", CharacterIntent.CALLED, BotIdentity.SUNNA, "Te escucho."),
    DialogueScene("cami-called-1", CharacterIntent.CALLED, BotIdentity.CAMI, "¿Sí? Decime qué necesitás."),
    DialogueScene("cami-called-2", CharacterIntent.CALLED, BotIdentity.CAMI, "Te escucho. Dame el dato concreto."),
    DialogueScene("chie-called-1", CharacterIntent.CALLED, BotIdentity.CHIE, "¿S-sí? ¿Necesitás algo?"),
    DialogueScene("chie-called-2", CharacterIntent.CALLED, BotIdentity.CHIE, "Te escucho... p-podemos verlo juntas."),
    DialogueScene("cari-affection-1", CharacterIntent.AFFECTION, BotIdentity.CARI, "Awww. Vení, te guardo un abrazo de capibara. ☕💛"),
    DialogueScene("cari-affection-2", CharacterIntent.AFFECTION, BotIdentity.CARI, "¡Qué lindo escuchar eso! Me alegra que estés acá."),
    DialogueScene("cari-reassurance-1", CharacterIntent.REASSURANCE, BotIdentity.CARI, "Sí, estoy bien. Pero ahora decime vos, ¿todo bien?"),
    DialogueScene("cari-reassurance-2", CharacterIntent.REASSURANCE, BotIdentity.CARI, "Estoy bien. Un poquito cansada, pero todavía puedo ayudar."),
    DialogueScene("cari-belonging-1", CharacterIntent.BELONGING, BotIdentity.CARI, "Claro que podés quedarte. ¡Esta mesa también es tuya!"),
    DialogueScene("cari-belonging-2", CharacterIntent.BELONGING, BotIdentity.CARI, "Quedate tranquilo. Hay lugar en el Café Otaku."),
    DialogueScene("cami-affection-1", CharacterIntent.AFFECTION, BotIdentity.CAMI, "Gracias. No siempre sé qué decir ante estas cosas, pero las valoro."),
    DialogueScene("cami-affection-2", CharacterIntent.AFFECTION, BotIdentity.CAMI, "Lo recordaré. Me alegra que confíes en mí."),
    DialogueScene("cami-reassurance-1", CharacterIntent.REASSURANCE, BotIdentity.CAMI, "Estoy bien. Gracias por preguntar antes de sacar conclusiones."),
    DialogueScene("cami-reassurance-2", CharacterIntent.REASSURANCE, BotIdentity.CAMI, "Todo está bien por ahora. Si cambia algo, te aviso."),
    DialogueScene("cami-belonging-1", CharacterIntent.BELONGING, BotIdentity.CAMI, "Podés quedarte. Todavía tengo trabajo, pero no molestas."),
    DialogueScene("cami-belonging-2", CharacterIntent.BELONGING, BotIdentity.CAMI, "Sí, hay lugar. Si querés, podés sentarte aquí."),
    DialogueScene("sunna-affection-1", CharacterIntent.AFFECTION, BotIdentity.SUNNA, "Gracias... me alegra."),
    DialogueScene("sunna-affection-2", CharacterIntent.AFFECTION, BotIdentity.SUNNA, "No estoy acostumbrada... pero me gusta."),
    DialogueScene("sunna-reassurance-1", CharacterIntent.REASSURANCE, BotIdentity.SUNNA, "Sí... estoy bien."),
    DialogueScene("sunna-reassurance-2", CharacterIntent.REASSURANCE, BotIdentity.SUNNA, "Un poco cansada. Pero estoy aquí."),
    DialogueScene("sunna-belonging-1", CharacterIntent.BELONGING, BotIdentity.SUNNA, "Sí... quedate."),
    DialogueScene("sunna-belonging-2", CharacterIntent.BELONGING, BotIdentity.SUNNA, "No molesta. Hay lugar."),
    DialogueScene("chie-affection-1", CharacterIntent.AFFECTION, BotIdentity.CHIE, "G-gracias... eso significa mucho para mí."),
    DialogueScene("chie-affection-2", CharacterIntent.AFFECTION, BotIdentity.CHIE, "N-no sé cómo responder, pero me hizo feliz."),
    DialogueScene("chie-reassurance-1", CharacterIntent.REASSURANCE, BotIdentity.CHIE, "S-sí... estoy bien. Solo estaba un poco nerviosa."),
    DialogueScene("chie-reassurance-2", CharacterIntent.REASSURANCE, BotIdentity.CHIE, "Todo está en orden. Gracias por estar pendiente."),
    DialogueScene("chie-belonging-1", CharacterIntent.BELONGING, BotIdentity.CHIE, "C-claro. Hay lugar para vos."),
    DialogueScene("chie-belonging-2", CharacterIntent.BELONGING, BotIdentity.CHIE, "Podés quedarte. Yo seguiré revisando la lista."),

    DialogueScene(
        "group-call-cari-sunna",
        CharacterIntent.BELONGING,
        BotIdentity.CARI,
        "Sunna, vení. Te guardé un lugar cerca de nosotras.",
        follow_up_speaker=BotIdentity.SUNNA,
        follow_up_text="Sí... voy.",
    ),
    DialogueScene(
        "group-call-cari-cami-support",
        CharacterIntent.REASSURANCE,
        BotIdentity.CARI,
        "Cami, necesito que me ayudes a pensar esto antes de hacer una locura.",
        follow_up_speaker=BotIdentity.CAMI,
        follow_up_text="Bien. Empezar por pedir ayuda ya es un buen dato.",
    ),
    DialogueScene(
        "group-call-cami-cari-check",
        CharacterIntent.REASSURANCE,
        BotIdentity.CAMI,
        "Cari, antes de decidir, escuchame un segundo.",
        follow_up_speaker=BotIdentity.CARI,
        follow_up_text="Te escucho. Esta vez no voy a salir corriendo primero.",
    ),
    DialogueScene(
        "group-call-cami-chie",
        CharacterIntent.HELP,
        BotIdentity.CAMI,
        "Chie, te ayudo con la lista. No tienes que hacer todo sola.",
        follow_up_speaker=BotIdentity.CHIE,
        follow_up_text="G-gracias. Me deja mucho más tranquila.",
    ),
    DialogueScene(
        "group-call-sunna-cari",
        CharacterIntent.AFFECTION,
        BotIdentity.SUNNA,
        "Cari... gracias por esperarme.",
        follow_up_speaker=BotIdentity.CARI,
        follow_up_text="Siempre. No hace falta que llegues corriendo.",
    ),
    DialogueScene(
        "group-call-sunna-cami",
        CharacterIntent.CONFUSION,
        BotIdentity.SUNNA,
        "Cami... no entiendo esto.",
        follow_up_speaker=BotIdentity.CAMI,
        follow_up_text="Está bien. Lo vemos juntas, paso a paso.",
    ),
    DialogueScene(
        "group-call-chie-cami",
        CharacterIntent.HELP,
        BotIdentity.CHIE,
        "Cami... ¿podés revisar esto conmigo antes de publicarlo?",
        follow_up_speaker=BotIdentity.CAMI,
        follow_up_text="Sí. Primero comprobamos los datos y después decidimos.",
    ),
    DialogueScene(
        "group-call-chie-sunna-comfort",
        CharacterIntent.REASSURANCE,
        BotIdentity.CHIE,
        "Sunna... podés quedarte aquí. No tienes que esconderte.",
        follow_up_speaker=BotIdentity.SUNNA,
        follow_up_text="Lo intentaré. Gracias.",
    ),


    DialogueScene(
        "group-call-cari-chie-help",
        CharacterIntent.HELP,
        BotIdentity.CARI,
        "Chie, ¿me ayudas con los avisos? Yo atiendo el café mientras vos ordenás la lista.",
        follow_up_speaker=BotIdentity.CHIE,
        follow_up_text="S-sí. Así puedo hacerlo sin apurarme.",
    ),
    DialogueScene(
        "group-call-chie-cari-help",
        CharacterIntent.HELP,
        BotIdentity.CHIE,
        "Cari... ¿podés dejarme la lista de mesas? Yo reviso los avisos.",
        follow_up_speaker=BotIdentity.CARI,
        follow_up_text="¡Sí! Te la dejo ordenada. Después hacemos juntas el resto.",
    ),
    DialogueScene(
        "group-call-cari-cami-check-2",
        CharacterIntent.CONFUSION,
        BotIdentity.CARI,
        "Cami... me parece que entendí mal. ¿Lo revisamos juntas?",
        follow_up_speaker=BotIdentity.CAMI,
        follow_up_text="Sí. Primero separamos lo que sabemos de lo que estamos suponiendo.",
    ),
    DialogueScene(
        "group-call-cami-cari-check-2",
        CharacterIntent.CONFUSION,
        BotIdentity.CAMI,
        "Cari, creo que estamos mezclando dos problemas distintos.",
        follow_up_speaker=BotIdentity.CARI,
        follow_up_text="Ah... sí. Me estaba adelantando otra vez.",
    ),
    DialogueScene(
        "group-call-sunna-cari-belonging",
        CharacterIntent.BELONGING,
        BotIdentity.SUNNA,
        "Cari... ¿todavía hay lugar?",
        follow_up_speaker=BotIdentity.CARI,
        follow_up_text="Siempre. Vení, te guardé sitio.",
    ),
    DialogueScene(
        "group-call-cari-sunna-belonging-2",
        CharacterIntent.BELONGING,
        BotIdentity.CARI,
        "Sunna, no hace falta que preguntes cada vez. Esta mesa es para todas.",
        follow_up_speaker=BotIdentity.SUNNA,
        follow_up_text="...Está bien. Gracias.",
    ),
    DialogueScene(
        "group-call-cami-sunna-curiosity",
        CharacterIntent.UNKNOWN_TOPIC,
        BotIdentity.CAMI,
        "Sunna, si querés, te muestro cómo funciona este juego.",
        follow_up_speaker=BotIdentity.SUNNA,
        follow_up_text="Sí. Quiero aprender.",
    ),
    DialogueScene(
        "group-call-sunna-cami-curiosity",
        CharacterIntent.UNKNOWN_TOPIC,
        BotIdentity.SUNNA,
        "Cami... ¿me enseñas otra vez?",
        follow_up_speaker=BotIdentity.CAMI,
        follow_up_text="Claro. Esta vez lo hacemos más despacio.",
    ),

    DialogueScene(
        "group-call-cari-cami-guidance",
        CharacterIntent.REASSURANCE,
        BotIdentity.CARI,
        "Cami, quedate conmigo un segundo. Quiero hacerlo bien.",
        follow_up_speaker=BotIdentity.CAMI,
        follow_up_text="Entonces lo hacemos juntas y revisamos lo importante.",
    ),
    DialogueScene(
        "group-call-cami-cari-care",
        CharacterIntent.AFFECTION,
        BotIdentity.CAMI,
        "Cari, no necesitas resolverlo todo antes de descansar.",
        follow_up_speaker=BotIdentity.CARI,
        follow_up_text="Lo sé... o al menos estoy intentando aprenderlo.",
    ),
    DialogueScene(
        "group-call-cari-sunna-welcome",
        CharacterIntent.REASSURANCE,
        BotIdentity.CARI,
        "Sunna, podés quedarte tranquila. Nadie espera que tengas todo resuelto.",
        follow_up_speaker=BotIdentity.SUNNA,
        follow_up_text="Eso ayuda. Gracias.",
    ),
    DialogueScene(
        "group-call-sunna-cari-gratitude",
        CharacterIntent.THANKS,
        BotIdentity.SUNNA,
        "Cari... gracias por invitarme.",
        follow_up_speaker=BotIdentity.CARI,
        follow_up_text="De nada. Vení cuando quieras.",
    ),
    DialogueScene(
        "group-call-cari-chie-support",
        CharacterIntent.HELP,
        BotIdentity.CARI,
        "Chie, decime qué parte de la lista querés que haga yo.",
        follow_up_speaker=BotIdentity.CHIE,
        follow_up_text="E-esa parte me vendría muy bien. Gracias.",
    ),
    DialogueScene(
        "group-call-chie-cari-pace",
        CharacterIntent.REASSURANCE,
        BotIdentity.CHIE,
        "Cari... podés ir un poco más despacio. Yo te sigo.",
        follow_up_speaker=BotIdentity.CARI,
        follow_up_text="Sí. Despacio también cuenta.",
    ),
    DialogueScene(
        "group-call-cami-sunna-quiet",
        CharacterIntent.BELONGING,
        BotIdentity.CAMI,
        "Sunna, si querés podés quedarte aquí mientras termino esto.",
        follow_up_speaker=BotIdentity.SUNNA,
        follow_up_text="Me quedaré un rato.",
    ),
    DialogueScene(
        "group-call-sunna-cami-trust",
        CharacterIntent.THANKS,
        BotIdentity.SUNNA,
        "Cami... gracias por explicarlo otra vez.",
        follow_up_speaker=BotIdentity.CAMI,
        follow_up_text="No tienes que disculparte. Podemos repetirlo.",
    ),
    DialogueScene(
        "group-call-cami-chie-check",
        CharacterIntent.REASSURANCE,
        BotIdentity.CAMI,
        "Chie, no hace falta que lo tengas perfecto antes de enseñármelo.",
        follow_up_speaker=BotIdentity.CHIE,
        follow_up_text="¿D-de verdad? Entonces te lo paso así.",
    ),
    DialogueScene(
        "group-call-chie-cami-thanks",
        CharacterIntent.THANKS,
        BotIdentity.CHIE,
        "Cami, gracias por revisar esto conmigo.",
        follow_up_speaker=BotIdentity.CAMI,
        follow_up_text="No hay problema. Prefiero comprobarlo contigo.",
    ),
    DialogueScene(
        "group-call-sunna-chie-quiet",
        CharacterIntent.BELONGING,
        BotIdentity.SUNNA,
        "Chie... ¿puedo sentarme aquí?",
        follow_up_speaker=BotIdentity.CHIE,
        follow_up_text="S-sí. Claro. Hay lugar.",
    ),
    DialogueScene(
        "group-call-chie-sunna-stay",
        CharacterIntent.REASSURANCE,
        BotIdentity.CHIE,
        "Sunna... no tienes que irte solo porque esté todo tranquilo.",
        follow_up_speaker=BotIdentity.SUNNA,
        follow_up_text="Entonces me quedaré.",
    ),

)
