from app.characters.models import CharacterIntent, DialogueScene
from app.core.identity import BotIdentity


REPERTOIRE: tuple[DialogueScene, ...] = (
    DialogueScene("cari-greeting-1", CharacterIntent.GREETING, BotIdentity.CARI, "¡Holaaa! ☕ ¿Llegaste al café para charlar un rato?"),
    DialogueScene("cari-greeting-2", CharacterIntent.GREETING, BotIdentity.CARI, "¡Bienvenido al Café Otaku! >_< ¿Qué vas a pedir?"),
    DialogueScene("cari-greeting-3", CharacterIntent.GREETING, BotIdentity.CARI, "Mmm, alguien acaba de entrar... ¡hola! ✨"),
    DialogueScene("cari-farewell-1", CharacterIntent.FAREWELL, BotIdentity.CARI, "¡Nos vemos luego! No te olvides de pasar por el café otra vez."),
    DialogueScene("cari-farewell-2", CharacterIntent.FAREWELL, BotIdentity.CARI, "Bye bye~ Guardamos tu mesa... más o menos. 😌"),
    DialogueScene("cari-thanks-1", CharacterIntent.THANKS, BotIdentity.CARI, "Jeje, de nada. Para eso está Cari. ☕"),
    DialogueScene("cari-help-1", CharacterIntent.HELP, BotIdentity.CARI, "Puedo ayudarte con cosas del café, anime, manga y recomendaciones."),
    DialogueScene("cari-unknown-1", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Mmm... no sé..... Cami, ayuda... *sale un poquito de humo de su cabeza* 💨"),
    DialogueScene("cari-unknown-2", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Eso ya está demasiado raro para Cari... ¿no será mejor preguntarle a Cami?"),
    DialogueScene("cari-unknown-3", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Eeeh... no tengo eso en mi libretito. *busca debajo del mostrador*"),
    DialogueScene("cari-outscope-1", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CARI, "Eso suena muy científico... Cari atiende el café, no un laboratorio. 😵‍💫"),
    DialogueScene("cari-busy-1", CharacterIntent.BUSY, BotIdentity.CARI, "Un segundo, estoy atendiendo una mesa. ¡Ya voy!"),
    DialogueScene("cari-quiet-1", CharacterIntent.QUIET, BotIdentity.CARI, "...Está demasiado tranquilo por aquí. 👀"),
    DialogueScene("cari-celebrate-1", CharacterIntent.CELEBRATION, BotIdentity.CARI, "¡Yay! ¡Eso merece un juguito especial! 🧃✨"),
    DialogueScene("cami-greeting-1", CharacterIntent.GREETING, BotIdentity.CAMI, "Buenos días. Café abierto. Registro iniciado."),
    DialogueScene("cami-greeting-2", CharacterIntent.GREETING, BotIdentity.CAMI, "Hola. Si buscas algo concreto, puedo revisar el archivo."),
    DialogueScene("cami-farewell-1", CharacterIntent.FAREWELL, BotIdentity.CAMI, "Hasta luego. Tu actividad quedó registrada correctamente."),
    DialogueScene("cami-thanks-1", CharacterIntent.THANKS, BotIdentity.CAMI, "No hay problema. De nada."),
    DialogueScene("cami-help-1", CharacterIntent.HELP, BotIdentity.CAMI, "Puedo revisar imágenes, etiquetas, pedidos, publicaciones y estadísticas."),
    DialogueScene("cami-unknown-1", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CAMI, "No tengo datos suficientes para afirmarlo."),
    DialogueScene("cami-unknown-2", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CAMI, "Ese tema no está registrado en mi archivo actual."),
    DialogueScene("cami-outscope-1", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CAMI, "No puedo verificar eso con los datos disponibles."),
    DialogueScene("cami-busy-1", CharacterIntent.BUSY, BotIdentity.CAMI, "Estoy terminando una tarea. Un momento."),
    DialogueScene("cami-confusion-1", CharacterIntent.CONFUSION, BotIdentity.CAMI, "La información no coincide. Voy a revisar el registro."),
    DialogueScene("chie-greeting-1", CharacterIntent.GREETING, BotIdentity.CHIE, "B-buenas... bienvenido al café. ¿Necesitas algo?"),
    DialogueScene("chie-farewell-1", CharacterIntent.FAREWELL, BotIdentity.CHIE, "Hasta luego. ¡Que tengas una buena tarde!"),
    DialogueScene("chie-help-1", CharacterIntent.HELP, BotIdentity.CHIE, "P-puedo ayudarte con la organización y los avisos del café."),
    DialogueScene("chie-unknown-1", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CHIE, "P-perdón... eso está fuera de mis posibilidades. *sonrisa nerviosa*"),
    DialogueScene("chie-unknown-2", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CHIE, "No estoy segura de eso... quizá Cami pueda comprobarlo."),
    DialogueScene("chie-outscope-1", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CHIE, "Eso no está dentro de mis tareas. P-perdón..."),
    DialogueScene("chie-busy-1", CharacterIntent.BUSY, BotIdentity.CHIE, "E-espera un momento, estoy revisando una lista."),
    DialogueScene("chie-apology-1", CharacterIntent.APOLOGY, BotIdentity.CHIE, "N-no pasa nada. Podemos arreglarlo con calma."),
    DialogueScene("sunna-greeting-1", CharacterIntent.GREETING, BotIdentity.SUNNA, "Hola."),
    DialogueScene("sunna-greeting-2", CharacterIntent.GREETING, BotIdentity.SUNNA, "Llegaste."),
    DialogueScene("sunna-farewell-1", CharacterIntent.FAREWELL, BotIdentity.SUNNA, "Hasta luego."),
    DialogueScene("sunna-thanks-1", CharacterIntent.THANKS, BotIdentity.SUNNA, "De nada."),
    DialogueScene("sunna-help-1", CharacterIntent.HELP, BotIdentity.SUNNA, "Puedo ayudarte con el juego."),
    DialogueScene("sunna-unknown-1", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.SUNNA, "No sé....."),
    DialogueScene("sunna-unknown-2", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.SUNNA, "No conozco eso."),
    DialogueScene("sunna-outscope-1", CharacterIntent.OUT_OF_SCOPE, BotIdentity.SUNNA, "Eso no es lo mío."),
    DialogueScene("sunna-busy-1", CharacterIntent.BUSY, BotIdentity.SUNNA, "Estoy jugando."),
    DialogueScene("sunna-quiet-1", CharacterIntent.QUIET, BotIdentity.SUNNA, "...Hm."),
    DialogueScene("sunna-celebrate-1", CharacterIntent.CELEBRATION, BotIdentity.SUNNA, "Bien."),
    DialogueScene("group-call-cari-cami", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Mmm... no sé..... Cami, ayuda...", follow_up_speaker=BotIdentity.CAMI, follow_up_text="Estoy aquí. ¿Qué necesitas comprobar?"),
    DialogueScene("group-call-cari-chie", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "No molestes a Cari -_- ... Casi ven a tomar un juguito.", follow_up_speaker=BotIdentity.CHIE, follow_up_text="P-perdón... ella volverá en un momento. Por favor, no pregunten cosas fuera de sus posibilidades. *sonrisa nerviosa*"),
)
