from app.characters.models import CharacterIntent, DialogueScene
from app.core.identity import BotIdentity


REPERTOIRE: tuple[DialogueScene, ...] = (
    DialogueScene("cari-greeting-1", CharacterIntent.GREETING, BotIdentity.CARI, "¡Holaaa! ☕ ¿Llegaste al café para charlar un rato?"),
    DialogueScene("cari-greeting-2", CharacterIntent.GREETING, BotIdentity.CARI, "¡Bienvenido al Café Otaku! >_< ¿Qué vas a pedir?"),
    DialogueScene("cari-greeting-3", CharacterIntent.GREETING, BotIdentity.CARI, "Mmm, alguien acaba de entrar... ¡hola! ✨"),
    DialogueScene("cari-farewell-1", CharacterIntent.FAREWELL, BotIdentity.CARI, "¡Nos vemos luego! No te olvides de pasar por el café otra vez."),
    DialogueScene("cari-farewell-2", CharacterIntent.FAREWELL, BotIdentity.CARI, "Bye bye~ Guardamos tu mesa... más o menos. 😌"),
    DialogueScene("cari-thanks-1", CharacterIntent.THANKS, BotIdentity.CARI, "Jeje, de nada. Para eso está Cari. ☕"),
    DialogueScene("cari-thanks-2", CharacterIntent.THANKS, BotIdentity.CARI, "No fue nada~ ¡Te guardo un lugar cerca de la ventana!"),
    DialogueScene("cari-help-1", CharacterIntent.HELP, BotIdentity.CARI, "Puedo ayudarte con cosas del café, anime, manga y recomendaciones."),
    DialogueScene("cari-help-2", CharacterIntent.HELP, BotIdentity.CARI, "Primero dime qué buscas y vemos quién del café puede ayudarte."),
    DialogueScene("cari-unknown-1", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Mmm... no sé..... Cami, ayuda... *sale un poquito de humo de su cabeza* 💨"),
    DialogueScene("cari-unknown-2", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Eso ya está demasiado raro para Cari... ¿no será mejor preguntarle a Cami?"),
    DialogueScene("cari-unknown-3", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Eeeh... no tengo eso en mi libretito. *busca debajo del mostrador*"),
    DialogueScene("cari-unknown-4", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Cari no sabe eso... todavía. O quizá nunca. *mira al techo*"),
    DialogueScene("cari-unknown-5", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Mmm... pregunta difícil. Voy a fingir que estaba atendiendo otra mesa. 👀"),
    DialogueScene("cari-outscope-1", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CARI, "Eso suena muy científico... Cari atiende el café, no un laboratorio. 😵‍💫"),
    DialogueScene("cari-outscope-2", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CARI, "Esa pregunta se escapó del menú. No la tenemos hoy."),
    DialogueScene("cari-outscope-3", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CARI, "¿Podemos volver a hablar de anime? Eso sí está dentro del turno de Cari."),
    DialogueScene("cari-busy-1", CharacterIntent.BUSY, BotIdentity.CARI, "Un segundo, estoy atendiendo una mesa. ¡Ya voy!"),
    DialogueScene("cari-busy-2", CharacterIntent.BUSY, BotIdentity.CARI, "¡Espera! Se me juntaron dos pedidos y una campanita..."),
    DialogueScene("cari-busy-3", CharacterIntent.BUSY, BotIdentity.CARI, "Estoy ocupada cinco minutos. Cinco minutos de verdad... creo."),
    DialogueScene("cari-quiet-1", CharacterIntent.QUIET, BotIdentity.CARI, "...Está demasiado tranquilo por aquí. 👀"),
    DialogueScene("cari-quiet-2", CharacterIntent.QUIET, BotIdentity.CARI, "¿Todos se fueron a dormir o qué? ☕"),
    DialogueScene("cari-celebrate-1", CharacterIntent.CELEBRATION, BotIdentity.CARI, "¡Yay! ¡Eso merece un juguito especial! 🧃✨"),
    DialogueScene("cari-celebrate-2", CharacterIntent.CELEBRATION, BotIdentity.CARI, "¡Victoria! Anótalo en la pizarrita del café."),

    DialogueScene("cami-greeting-1", CharacterIntent.GREETING, BotIdentity.CAMI, "Buenos días. Café abierto. Registro iniciado."),
    DialogueScene("cami-greeting-2", CharacterIntent.GREETING, BotIdentity.CAMI, "Hola. Si buscas algo concreto, puedo revisar el archivo."),
    DialogueScene("cami-greeting-3", CharacterIntent.GREETING, BotIdentity.CAMI, "Bienvenido. Dime qué necesitas y comprobaré las existencias."),
    DialogueScene("cami-farewell-1", CharacterIntent.FAREWELL, BotIdentity.CAMI, "Hasta luego. Tu actividad quedó registrada correctamente."),
    DialogueScene("cami-farewell-2", CharacterIntent.FAREWELL, BotIdentity.CAMI, "Hasta la próxima. El archivo seguirá disponible."),
    DialogueScene("cami-thanks-1", CharacterIntent.THANKS, BotIdentity.CAMI, "No hay problema. De nada."),
    DialogueScene("cami-thanks-2", CharacterIntent.THANKS, BotIdentity.CAMI, "Acepto el agradecimiento. La tarea era sencilla."),
    DialogueScene("cami-help-1", CharacterIntent.HELP, BotIdentity.CAMI, "Puedo revisar imágenes, etiquetas, pedidos, publicaciones y estadísticas."),
    DialogueScene("cami-help-2", CharacterIntent.HELP, BotIdentity.CAMI, "Dame el dato concreto. Buscaré el registro correspondiente."),
    DialogueScene("cami-unknown-1", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CAMI, "No tengo datos suficientes para afirmarlo."),
    DialogueScene("cami-unknown-2", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CAMI, "Ese tema no está registrado en mi archivo actual."),
    DialogueScene("cami-unknown-3", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CAMI, "Necesito una fuente o un registro antes de responder."),
    DialogueScene("cami-outscope-1", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CAMI, "No puedo verificar eso con los datos disponibles."),
    DialogueScene("cami-outscope-2", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CAMI, "Eso no pertenece a mi archivo operativo."),
    DialogueScene("cami-busy-1", CharacterIntent.BUSY, BotIdentity.CAMI, "Estoy terminando una tarea. Un momento."),
    DialogueScene("cami-busy-2", CharacterIntent.BUSY, BotIdentity.CAMI, "Tengo una cola de trabajo pendiente. Responderé cuando termine la revisión."),
    DialogueScene("cami-confusion-1", CharacterIntent.CONFUSION, BotIdentity.CAMI, "La información no coincide. Voy a revisar el registro."),
    DialogueScene("cami-confusion-2", CharacterIntent.CONFUSION, BotIdentity.CAMI, "Hay una inconsistencia. No voy a asumir cuál dato es correcto."),
    DialogueScene("cami-quiet-1", CharacterIntent.QUIET, BotIdentity.CAMI, "Archivo en pausa. No hay tareas urgentes."),
    DialogueScene("cami-quiet-2", CharacterIntent.QUIET, BotIdentity.CAMI, "La revisión terminó. El archivo queda tranquilo por ahora."),
    DialogueScene("cami-celebrate-1", CharacterIntent.CELEBRATION, BotIdentity.CAMI, "Registro completado. Resultado satisfactorio."),

    DialogueScene("chie-greeting-1", CharacterIntent.GREETING, BotIdentity.CHIE, "B-buenas... bienvenido al café. ¿Necesitas algo?"),
    DialogueScene("chie-greeting-2", CharacterIntent.GREETING, BotIdentity.CHIE, "H-hola... todo está preparado. Creo."),
    DialogueScene("chie-greeting-3", CharacterIntent.GREETING, BotIdentity.CHIE, "Buenas... por favor, avísame si necesitas ayuda con algo."),
    DialogueScene("chie-farewell-1", CharacterIntent.FAREWELL, BotIdentity.CHIE, "Hasta luego. ¡Que tengas una buena tarde!"),
    DialogueScene("chie-farewell-2", CharacterIntent.FAREWELL, BotIdentity.CHIE, "H-hasta pronto. No olvides revisar los avisos del café."),
    DialogueScene("chie-thanks-1", CharacterIntent.THANKS, BotIdentity.CHIE, "D-de nada. Me alegra poder ayudar."),
    DialogueScene("chie-help-1", CharacterIntent.HELP, BotIdentity.CHIE, "P-puedo ayudarte con la organización y los avisos del café."),
    DialogueScene("chie-help-2", CharacterIntent.HELP, BotIdentity.CHIE, "Dime qué necesitas y buscaré a la persona adecuada."),
    DialogueScene("chie-unknown-1", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CHIE, "P-perdón... eso está fuera de mis posibilidades. *sonrisa nerviosa*"),
    DialogueScene("chie-unknown-2", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CHIE, "No estoy segura de eso... quizá Cami pueda comprobarlo."),
    DialogueScene("chie-unknown-3", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CHIE, "E-es una pregunta complicada... no quiero darte información equivocada."),
    DialogueScene("chie-outscope-1", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CHIE, "Eso no está dentro de mis tareas. P-perdón..."),
    DialogueScene("chie-outscope-2", CharacterIntent.OUT_OF_SCOPE, BotIdentity.CHIE, "No sé cómo resolver eso. Mejor lo dejamos para alguien que sí pueda."),
    DialogueScene("chie-busy-1", CharacterIntent.BUSY, BotIdentity.CHIE, "E-espera un momento, estoy revisando una lista."),
    DialogueScene("chie-busy-2", CharacterIntent.BUSY, BotIdentity.CHIE, "Tengo varios avisos pendientes... dame un momento, por favor."),
    DialogueScene("chie-apology-1", CharacterIntent.APOLOGY, BotIdentity.CHIE, "N-no pasa nada. Podemos arreglarlo con calma."),
    DialogueScene("chie-apology-2", CharacterIntent.APOLOGY, BotIdentity.CHIE, "P-perdón por el desorden. Ya estoy revisándolo."),
    DialogueScene("chie-quiet-1", CharacterIntent.QUIET, BotIdentity.CHIE, "Ya revisé los avisos. Por ahora está todo en orden."),
    DialogueScene("chie-quiet-2", CharacterIntent.QUIET, BotIdentity.CHIE, "E-está tranquilo... así puedo terminar la lista sin problemas."),
    DialogueScene("chie-celebrate-1", CharacterIntent.CELEBRATION, BotIdentity.CHIE, "¡S-salió bien! Eso... eso es bueno. *sonríe nerviosa*"),

    DialogueScene("sunna-greeting-1", CharacterIntent.GREETING, BotIdentity.SUNNA, "Hola."),
    DialogueScene("sunna-greeting-2", CharacterIntent.GREETING, BotIdentity.SUNNA, "Llegaste."),
    DialogueScene("sunna-greeting-3", CharacterIntent.GREETING, BotIdentity.SUNNA, "Hm. Hola."),
    DialogueScene("sunna-farewell-1", CharacterIntent.FAREWELL, BotIdentity.SUNNA, "Hasta luego."),
    DialogueScene("sunna-farewell-2", CharacterIntent.FAREWELL, BotIdentity.SUNNA, "Nos vemos."),
    DialogueScene("sunna-thanks-1", CharacterIntent.THANKS, BotIdentity.SUNNA, "De nada."),
    DialogueScene("sunna-thanks-2", CharacterIntent.THANKS, BotIdentity.SUNNA, "No importa."),
    DialogueScene("sunna-help-1", CharacterIntent.HELP, BotIdentity.SUNNA, "Puedo ayudarte con el juego."),
    DialogueScene("sunna-help-2", CharacterIntent.HELP, BotIdentity.SUNNA, "Dime qué juego."),
    DialogueScene("sunna-unknown-1", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.SUNNA, "No sé....."),
    DialogueScene("sunna-unknown-2", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.SUNNA, "No conozco eso."),
    DialogueScene("sunna-unknown-3", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.SUNNA, "Hm... no sé."),
    DialogueScene("sunna-outscope-1", CharacterIntent.OUT_OF_SCOPE, BotIdentity.SUNNA, "Eso no es lo mío."),
    DialogueScene("sunna-outscope-2", CharacterIntent.OUT_OF_SCOPE, BotIdentity.SUNNA, "No me interesa ese tema."),
    DialogueScene("sunna-busy-1", CharacterIntent.BUSY, BotIdentity.SUNNA, "Estoy jugando."),
    DialogueScene("sunna-busy-2", CharacterIntent.BUSY, BotIdentity.SUNNA, "Espera. Estoy en una partida."),
    DialogueScene("sunna-quiet-1", CharacterIntent.QUIET, BotIdentity.SUNNA, "...Hm."),
    DialogueScene("sunna-quiet-2", CharacterIntent.QUIET, BotIdentity.SUNNA, "Está tranquilo."),
    DialogueScene("sunna-confusion-1", CharacterIntent.CONFUSION, BotIdentity.SUNNA, "No entiendo."),
    DialogueScene("sunna-celebrate-1", CharacterIntent.CELEBRATION, BotIdentity.SUNNA, "Bien."),
    DialogueScene("sunna-celebrate-2", CharacterIntent.CELEBRATION, BotIdentity.SUNNA, "Ganamos."),
    DialogueScene("sunna-thanks-3", CharacterIntent.THANKS, BotIdentity.SUNNA, "Gracias por quedarte."),
    DialogueScene("sunna-thanks-4", CharacterIntent.THANKS, BotIdentity.SUNNA, "Me gustó compartirlo."),
    DialogueScene("sunna-help-3", CharacterIntent.HELP, BotIdentity.SUNNA, "Puedo enseñarte. Despacio."),
    DialogueScene("sunna-unknown-4", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.SUNNA, "Quiero saber qué es."),
    DialogueScene("sunna-unknown-5", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.SUNNA, "Nunca había visto eso."),
    DialogueScene("sunna-quiet-3", CharacterIntent.QUIET, BotIdentity.SUNNA, "Me gusta cuando está tranquilo."),
    DialogueScene("sunna-celebrate-3", CharacterIntent.CELEBRATION, BotIdentity.SUNNA, "Fue divertido."),

    DialogueScene("group-call-cari-cami", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "Mmm... no sé..... Cami, ayuda...", follow_up_speaker=BotIdentity.CAMI, follow_up_text="Estoy aquí. ¿Qué necesitas comprobar?"),
    DialogueScene("group-call-cari-chie", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CARI, "No molestes a Cari -_- ... Casi ven a tomar un juguito.", follow_up_speaker=BotIdentity.CHIE, follow_up_text="P-perdón... ella volverá en un momento. Por favor, no pregunten cosas fuera de sus posibilidades. *sonrisa nerviosa*"),
    DialogueScene("group-call-cami-sunna", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.CAMI, "Sunna, si quieres podemos revisarlo juntas. Sin prisa.", follow_up_speaker=BotIdentity.SUNNA, follow_up_text="Sí... me gustaría."),
    DialogueScene("group-call-sunna-chie", CharacterIntent.UNKNOWN_TOPIC, BotIdentity.SUNNA, "Chie... ¿puedo quedarme aquí un rato?", follow_up_speaker=BotIdentity.CHIE, follow_up_text="S-sí. Claro. Puedes quedarte todo el tiempo que necesites."),
)
